version: "3"
services:
  ghost:
    image: ghost:1-alpine
    environment:
      - databaseClient=mysql
      - database_connection_database=ghost
      - database_connection_host=db
      - database_connection_user=root
      - database__connection__password=default
    restart: always
    ports:
      - 2368:2368
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}"
