// GENERAL

const PORT = process.env.PORT || 3000;

// HTTP STATUS CODE

const HTTP_OK_STATUS = 200;
const HTTP_CREATED_STATUS = 201;
const HTTP_BAD_REQUEST_STATUS = 400;
const HTTP_NOT_FOUND_STATUS = 404;
const HTTP_CONFLICT_STATUS = 409;
const HTTP_INTERNAL_SERVER_ERROR = 500;

module.exports = {
  PORT,
  HTTP_OK_STATUS,
  HTTP_CREATED_STATUS,
  HTTP_BAD_REQUEST_STATUS,
  HTTP_NOT_FOUND_STATUS,
  HTTP_CONFLICT_STATUS,
  HTTP_INTERNAL_SERVER_ERROR,
};
